export const stateData = [
  { id: "AN", value: "AN", name: "Andaman and Nicobar Islands" },
  { id: "AP", value: "AP", name: "Andhra Pradesh" },
  { id: "AR", value: "AR", name: "Arunachal Pradesh" },
  { id: "AS", value: "AS", name: "Assam" },
  { id: "BR", value: "BR", name: "Bihar" },
  { id: "CG", value: "CG", name: "Chandigarh" },
  { id: "CH", value: "CH", name: "Chhattisgarh" },
  { id: "DH", value: "DH", name: "Dadra and Nagar Haveli" },
  { id: "DD", value: "DD", name: "Daman and Diu" },
  { id: "DL", value: "DL", name: "Delhi" },
  { id: "GA", value: "GA", name: "Goa" },
  { id: "GJ", value: "GJ", name: "Gujarat" },
  { id: "HR", value: "HR", name: "Haryana" },
  { id: "HP", value: "HP", name: "Himachal Pradesh" },
  { id: "JK", value: "JK", name: "Jammu and Kashmir" },
  { id: "JH", value: "JH", name: "Jharkhand" },
  { id: "KA", value: "KA", name: "Karnataka" },
  { id: "KL", value: "KL", name: "Kerala" },
  { id: "LA", value: "LA", name: "Ladakh" },
  { id: "LD", value: "LD", name: "Lakshadweep" },
  { id: "MP", value: "MP", name: "Madhya Pradesh" },
  { id: "MH", value: "MH", name: "Maharashtra" },
  { id: "MN", value: "MN", name: "Manipur" },
  { id: "ML", value: "ML", name: "Meghalaya" },
  { id: "MZ", value: "MZ", name: "Mizoram" },
  { id: "NL", value: "NL", name: "Nagaland" },
  { id: "OR", value: "OR", name: "Odisha" },
  { id: "PY", value: "PY", name: "Puducherry" },
  { id: "PB", value: "PB", name: "Punjab" },
  { id: "RJ", value: "RJ", name: "Rajasthan" },
  { id: "SK", value: "SK", name: "Sikkim" },
  { id: "TN", value: "TN", name: "Tamil Nadu" },
  { id: "TG", value: "TG", name: "Telangana" },
  { id: "TR", value: "TR", name: "Tripura" },
  { id: "UT", value: "UT", name: "Uttarakhand" },
  { id: "UP", value: "UP", name: "Uttar Pradesh" },
  { id: "WB", value: "WB", name: "West Bengal" },
];
